version: 0.2

phases:
  install:
    commands:
      - echo "Installing terraform"
      - yum install -y yum-utils git jq zip unzip
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - echo "Terraform installation successful" 