version: 0.2

phases:
  install:
    commands:
      - echo "Installing terraform"
      - yum install -y yum-utils git jq zip unzip
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - echo "Terraform installation successful"
      - echo "Installing terrascan"
      - curl -L "$(curl -s https://api.github.com/repositories/103084166/releases/latest | grep -o -E 'https://.+?_Linux_x86_64.tar.gz')" > terrascan.tar.gz
      - tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
      - install terrascan /usr/local/bin && rm terrascan
  build:
    commands:

  artifacts:
  files:
    - '**/*'